spring:
  datasource:
    url: jdbc:h2:mem:sopoomshop
    username: sa
    password :
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      # application 실행 시점에 entity 를 지우고 자동 테이블 생성
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # Lazy Loading 시

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.ddingcode.sopoomshop.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.ddingcode.sopoomshop.mapper : trace