drop table if exists members cascade;

create table members
(
    MEMBER_ID bigint generated by default as identity,
    NAME varchar(10),
    ADDRESS varchar(100),
    PHONE varchar(100),
    PRIMARY KEY (MEMBER_ID)
)
;

create table items
(
    ITEM_ID bigint generated by default as identity,
    NAME varchar(10),
    BUY_PRICE INTEGER,
    SALE_PRICE INTEGER,
    STOCK INTEGER,
    PRIMARY KEY(ITEM_ID)
)
;

create table orders
(
    ORDER_ID bigint generated by default as identity,
    MEMBER_ID bigint,
    ITEM_ID  bigint,
    QUANTITY INTEGER,
    FOREIGN KEY (MEMBER_ID) REFERENCES members(MEMBER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES items(ITEM_ID)
);

-- alter table orders ADD CONSTRAINT 외래기 FOREIGN KEY (MEMBER_ID, ITEM_ID)